<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserRank(User $user)
    {
        return $this->createQueryBuilder('u')
            ->select('count(u.id)')
            ->where('u.points > :points')
            ->setParameter('points', $user->getPoints())
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }

    public function getTop100()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.points', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(100)
            ->getQuery()
            ->getResult()
            ;
    }
}
